WINDOW_WIDTH, WINDOW_HEIGHT = 800, 600
RESOLUTION = WINDOW_WIDTH, WINDOW_HEIGHT
FPS = 30

ROWS, COLS = 2, 2
BTN_WIDTH, BTN_HIGHT = WINDOW_WIDTH / COLS, WINDOW_HEIGHT / ROWS

GREEN = 'green'
GREEN_ACTIVE = 'green2'
BLUE = 'blue'
BLUE_ACTIVE = 'blue2'
RED = 'red'
RED_ACTIVE = 'red2'
ORANGE = 'orange'
ORANGE_ACTIVE = 'orange2'
